def testException(self):
    self.client.testException('Safe')
    try:
        self.client.testException('Xception')
        self.fail('should have gotten exception')
    except Xception as x:
        self.assertEqual(x.errorCode, 1001)
        self.assertEqual(x.message, 'Xception')
    try:
        self.client.testException('throw_undeclared')
        self.fail('should have thrown exception')
    except Exception:
        pass
